FROM node:20-bullseye-slim
WORKDIR /app

RUN apt-get update \
  && apt-get install -y --no-install-recommends python3 make g++ \
  && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install && npm prune --omit=dev

COPY server ./server
COPY data ./data

EXPOSE 3001
CMD ["npm", "run", "start"]
