FROM node:20-bullseye-slim
WORKDIR /app

RUN apt-get update \
  && apt-get install -y --no-install-recommends python3 make g++ \
  && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install

COPY index.html ./
COPY vite.config.js ./
COPY src ./src

EXPOSE 5173
CMD ["npm", "run", "dev:client", "--", "--host", "0.0.0.0"]
